import type { InspireItem } from "@/lib/inspire-types";

/** Curated trending catalog — posters enriched server-side via Wikipedia / TMDB. */
export const INSPIRE_CATALOG: InspireItem[] = [
  {
    id: "movie-dune-2",
    mediaType: "movie",
    tmdbId: 693134,
    wikiTitle: "Dune: Part Two",
    title: { ar: "كثيب: جزء ثاني", en: "Dune: Part Two" },
    year: 2024,
    genres: ["sci-fi", "action", "drama"],
    overview: {
      ar: "بول Atreides ينضم إلى Fremen في صحراء Arrakis لمواجهة House Harkonnen.",
      en: "Paul Atreides unites with the Fremen on Arrakis to confront House Harkonnen.",
    },
    posterPath: null,
    trending: true,
    rating: 8.4,
  },
  {
    id: "movie-oppenheimer",
    mediaType: "movie",
    tmdbId: 872585,
    wikiTitle: "Oppenheimer (film)",
    title: { ar: "أوبنهايمر", en: "Oppenheimer" },
    year: 2023,
    genres: ["drama", "thriller"],
    overview: {
      ar: "قصة فيزيائي يقود مشروع Manhattan ويغيّر مسار التاريخ.",
      en: "The physicist who led the Manhattan Project and changed history.",
    },
    posterPath: null,
    trending: true,
    rating: 8.1,
  },
  {
    id: "movie-deadpool-wolverine",
    mediaType: "movie",
    tmdbId: 533535,
    wikiTitle: "Deadpool & Wolverine",
    title: { ar: "ديدبول وولفرين", en: "Deadpool & Wolverine" },
    year: 2024,
    genres: ["action", "comedy", "sci-fi"],
    overview: {
      ar: "Deadpool ينضم إلى Wolverine في مغامرة multiverse مليئة بالفوضى.",
      en: "Deadpool teams with Wolverine in a chaotic multiverse adventure.",
    },
    posterPath: null,
    trending: true,
    rating: 7.6,
  },
  {
    id: "movie-wicked",
    mediaType: "movie",
    tmdbId: 402431,
    wikiTitle: "Wicked (2024 film)",
    title: { ar: "Wicked", en: "Wicked" },
    year: 2024,
    genres: ["fantasy", "romance", "drama"],
    overview: {
      ar: "قصة أصل Elphaba وGlinda قبل أن تصبحا ساحرتي Oz.",
      en: "The origin of Elphaba and Glinda before they became the witches of Oz.",
    },
    posterPath: null,
    trending: true,
    rating: 7.5,
  },
  {
    id: "movie-gladiator-2",
    mediaType: "movie",
    tmdbId: 558449,
    wikiTitle: "Gladiator II",
    title: { ar: "المصارع 2", en: "Gladiator II" },
    year: 2024,
    genres: ["action", "drama"],
    overview: {
      ar: "Lucius يعود إلى Rome كمُصارع يطلب الانتقام من الإمبراطورية.",
      en: "Lucius returns to Rome as a gladiator seeking vengeance against the empire.",
    },
    posterPath: null,
    trending: true,
    rating: 6.8,
  },
  {
    id: "movie-nosferatu",
    mediaType: "movie",
    tmdbId: 426426,
    wikiTitle: "Nosferatu (2024 film)",
    title: { ar: "نوسفيراتو", en: "Nosferatu" },
    year: 2024,
    genres: ["horror", "fantasy"],
    overview: {
      ar: "إعادة تخيل gothic لقصة مصاص الدماء الكلاسيكية بأجواء مرعبة.",
      en: "A gothic reimagining of the classic vampire tale with haunting atmosphere.",
    },
    posterPath: null,
    trending: true,
    rating: 7.2,
  },
  {
    id: "movie-anora",
    mediaType: "movie",
    tmdbId: 1069656,
    wikiTitle: "Anora (film)",
    title: { ar: "أنورا", en: "Anora" },
    year: 2024,
    genres: ["drama", "romance", "comedy"],
    overview: {
      ar: "راقصة من Brooklyn تتزوج ابن oligarch روسي فجأة — ثم تبدأ الفوضى.",
      en: "A Brooklyn dancer marries a Russian oligarch's son — then chaos unfolds.",
    },
    posterPath: null,
    trending: true,
    rating: 7.4,
  },
  {
    id: "movie-substance",
    mediaType: "movie",
    tmdbId: 933260,
    wikiTitle: "The Substance",
    title: { ar: "The Substance", en: "The Substance" },
    year: 2024,
    genres: ["horror", "sci-fi", "thriller"],
    overview: {
      ar: "دواء سري يمنح نسخة أصغر وأجمل — لكن الثمن مرعب.",
      en: "A secret drug creates a younger, better self — with a terrifying price.",
    },
    posterPath: null,
    trending: true,
    rating: 7.3,
  },
  {
    id: "movie-wild-robot",
    mediaType: "movie",
    tmdbId: 1184918,
    wikiTitle: "The Wild Robot (film)",
    title: { ar: "الروبوت البري", en: "The Wild Robot" },
    year: 2024,
    genres: ["animation", "sci-fi", "drama"],
    overview: {
      ar: "روبوت يتعلم البقاء في جزيرة بريّة ويربي Gosling.",
      en: "A robot learns to survive on a wild island and raises a gosling.",
    },
    posterPath: null,
    trending: false,
    rating: 8.0,
  },
  {
    id: "movie-conclave",
    mediaType: "movie",
    tmdbId: 968051,
    wikiTitle: "Conclave (film)",
    title: { ar: "Conclave", en: "Conclave" },
    year: 2024,
    genres: ["thriller", "drama"],
    overview: {
      ar: "Cardinals ينعقدون سراً لانتخاب Pope جديد — والمؤامرات تتكشف.",
      en: "Cardinals gather in secret to elect a new Pope as conspiracies unravel.",
    },
    posterPath: null,
    trending: false,
    rating: 7.4,
  },
  {
    id: "movie-moana-2",
    mediaType: "movie",
    tmdbId: 1241982,
    wikiTitle: "Moana 2",
    title: { ar: "موانا 2", en: "Moana 2" },
    year: 2024,
    genres: ["animation", "fantasy", "action"],
    overview: {
      ar: "Moana تبحر مجدداً مع Maui في رحلة جديدة عبر المحيط.",
      en: "Moana sails again with Maui on a new voyage across the ocean.",
    },
    posterPath: null,
    trending: true,
    rating: 7.0,
  },
  {
    id: "movie-beetlejuice-2",
    mediaType: "movie",
    tmdbId: 917496,
    wikiTitle: "Beetlejuice Beetlejuice",
    title: { ar: "Beetlejuice Beetlejuice", en: "Beetlejuice Beetlejuice" },
    year: 2024,
    genres: ["comedy", "fantasy", "horror"],
    overview: {
      ar: "عودة الشبح المشاغب Beetlejuice إلى Winter River بعد حادث مأساوي.",
      en: "The mischievous ghost Beetlejuice returns to Winter River after tragedy.",
    },
    posterPath: null,
    trending: false,
    rating: 6.9,
  },
  {
    id: "tv-squid-game-2",
    mediaType: "tv",
    tmdbId: 93405,
    wikiTitle: "Squid Game",
    title: { ar: "لعبة الحبار 2", en: "Squid Game Season 2" },
    year: 2024,
    genres: ["thriller", "drama", "action"],
    overview: {
      ar: "Gi-hun يعود للألعاب القاتلة بحثاً عن الحقيقة والانتقام.",
      en: "Gi-hun returns to the deadly games seeking truth and revenge.",
    },
    posterPath: null,
    trending: true,
    rating: 7.5,
  },
  {
    id: "tv-shogun",
    mediaType: "tv",
    tmdbId: 126308,
    wikiTitle: "Shōgun (2024 TV series)",
    title: { ar: "Shōgun", en: "Shōgun" },
    year: 2024,
    genres: ["drama", "action"],
    overview: {
      ar: "ملّاح إنجليزي يُلقي بظلاله على Japan في عصر Feudal.",
      en: "An English navigator lands in feudal Japan and reshapes its fate.",
    },
    posterPath: null,
    trending: true,
    rating: 8.6,
  },
  {
    id: "tv-fallout",
    mediaType: "tv",
    tmdbId: 106379,
    wikiTitle: "Fallout (American TV series)",
    title: { ar: "Fallout", en: "Fallout" },
    year: 2024,
    genres: ["sci-fi", "action", "drama"],
    overview: {
      ar: "بعد apocalypse نووي، Lucy تغادر Vault للبحث عن والدها.",
      en: "After nuclear apocalypse, Lucy leaves her Vault to find her father.",
    },
    posterPath: null,
    trending: true,
    rating: 8.4,
  },
  {
    id: "tv-house-dragon",
    mediaType: "tv",
    tmdbId: 94997,
    wikiTitle: "House of the Dragon",
    title: { ar: "House of the Dragon", en: "House of the Dragon" },
    year: 2024,
    genres: ["fantasy", "drama", "action"],
    overview: {
      ar: "صراع Targaryen على العرش قبل Game of Thrones.",
      en: "The Targaryen civil war for the Iron Throne before Game of Thrones.",
    },
    posterPath: null,
    trending: true,
    rating: 8.0,
  },
  {
    id: "tv-last-of-us",
    mediaType: "tv",
    tmdbId: 100088,
    wikiTitle: "The Last of Us (TV series)",
    title: { ar: "The Last of Us", en: "The Last of Us" },
    year: 2025,
    genres: ["drama", "sci-fi", "thriller"],
    overview: {
      ar: "Joel وEllie يواصلان رحلتهما في عالم post-apocalyptic.",
      en: "Joel and Ellie continue their journey in a ravaged world.",
    },
    posterPath: null,
    trending: true,
    rating: 8.5,
  },
  {
    id: "tv-penguin",
    mediaType: "tv",
    tmdbId: 194764,
    wikiTitle: "The Penguin (TV series)",
    title: { ar: "The Penguin", en: "The Penguin" },
    year: 2024,
    genres: ["crime", "drama", "thriller"],
    overview: {
      ar: "Oswald Cobblepot يصعد في عالم الجريمة في Gotham.",
      en: "Oswald Cobblepot rises in Gotham's underworld.",
    },
    posterPath: null,
    trending: true,
    rating: 8.2,
  },
  {
    id: "tv-arcane-2",
    mediaType: "tv",
    tmdbId: 94605,
    wikiTitle: "Arcane (TV series)",
    title: { ar: "Arcane الموسم 2", en: "Arcane Season 2" },
    year: 2024,
    genres: ["animation", "fantasy", "action"],
    overview: {
      ar: "Jinx وVi في مواجهة حاسمة بين Piltover وZaun.",
      en: "Jinx and Vi face a decisive clash between Piltover and Zaun.",
    },
    posterPath: null,
    trending: true,
    rating: 8.7,
  },
  {
    id: "tv-wednesday",
    mediaType: "tv",
    tmdbId: 119051,
    wikiTitle: "Wednesday (TV series)",
    title: { ar: "Wednesday", en: "Wednesday" },
    year: 2025,
    genres: ["comedy", "fantasy", "crime"],
    overview: {
      ar: "Wednesday Addams تحل ألغازاً غامضة في Nevermore Academy.",
      en: "Wednesday Addams unravels dark mysteries at Nevermore Academy.",
    },
    posterPath: null,
    trending: true,
    rating: 8.0,
  },
  {
    id: "tv-reacher",
    mediaType: "tv",
    tmdbId: 108978,
    wikiTitle: "Reacher (TV series)",
    title: { ar: "Reacher", en: "Reacher" },
    year: 2025,
    genres: ["action", "crime", "thriller"],
    overview: {
      ar: "Jack Reacher يحل جرائم بقبضة حديدية.",
      en: "Ex-military investigator Jack Reacher solves crimes with brutal efficiency.",
    },
    posterPath: null,
    trending: false,
    rating: 8.1,
  },
  {
    id: "tv-slow-horses",
    mediaType: "tv",
    tmdbId: 95480,
    wikiTitle: "Slow Horses (TV series)",
    title: { ar: "Slow Horses", en: "Slow Horses" },
    year: 2024,
    genres: ["thriller", "crime", "drama"],
    overview: {
      ar: "فريق MI5 منفى يُدار بقسوة من Jackson Lamb.",
      en: "A disgraced MI5 team is run ruthlessly by Jackson Lamb.",
    },
    posterPath: null,
    trending: false,
    rating: 8.3,
  },
  {
    id: "tv-bear",
    mediaType: "tv",
    tmdbId: 136315,
    wikiTitle: "The Bear (TV series)",
    title: { ar: "The Bear", en: "The Bear" },
    year: 2024,
    genres: ["drama", "comedy"],
    overview: {
      ar: "Carmy يحاول إنقاذ مطعم العائلة في Chicago.",
      en: "Carmy tries to save the family restaurant in Chicago.",
    },
    posterPath: null,
    trending: false,
    rating: 8.5,
  },
  {
    id: "tv-one-piece",
    mediaType: "tv",
    tmdbId: 111110,
    wikiTitle: "One Piece (2023 TV series)",
    title: { ar: "One Piece", en: "One Piece (Live Action)" },
    year: 2025,
    genres: ["action", "fantasy", "comedy"],
    overview: {
      ar: "Luffy وطاقمه يبحرون بحثاً عن One Piece.",
      en: "Luffy and his crew sail the Grand Line in search of the One Piece.",
    },
    posterPath: null,
    trending: true,
    rating: 8.2,
  },
];

export function mergeInspireItems(primary: InspireItem[], fallback: InspireItem[]): InspireItem[] {
  const seen = new Set<string>();
  const out: InspireItem[] = [];
  for (const item of [...primary, ...fallback]) {
    if (seen.has(item.id)) continue;
    seen.add(item.id);
    out.push(item);
  }
  return out;
}
